apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-forms
  labels:
    {{- include "oga-backend.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.forms }}
  {{ $key | quote }}: |-
{{ $value | indent 4 }}
{{- end }}
