{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "oga-backend.fullname" . }}
  labels:
    {{- include "oga-backend.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host | default (printf "%s-%s.%s" .Release.Name .Release.Namespace .Values.global.clusterDomain) }}
  to:
    kind: Service
    name: {{ include "oga-backend.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
{{- end }}
